### ISSUE TITLE
Алиса не понимает, что делать, когда слышит "нет"

### ISSUE THREAD

**Issue by safarikon** [kontur-1c/AliceDiary#44]
После прочтения расписания Алиса предлагает его повторить.
Я говорю "Нет" и мой ответ распознается.
Алиса не понимает его и просит повторить.
![image](https://user-images.githubusercontent.com/89935946/135894302-03ce43e1-18b6-4c91-b294-38ac9e2e106f.png)

**Comment by KrapivinAndrey** [comment]
поправил в текущей версии
